version: "3.9"
services:
  neo4j:
    image: neo4j:5.26
    container_name: neo4j
    ports:
      - "7474:7474"   # Browser interface
      - "7687:7687"   # Bolt protocol
    environment:
      - NEO4J_AUTH=${NEO4J_USER:-neo4j}/${NEO4J_PASSWORD:-graphiti}
    volumes:
      - ./neo4j_data:/data
      - ./neo4j_logs:/logs
    restart: unless-stopped
